name: Validate TEI documents

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "tei/*.xml"
  push:
    branches: [main]
    paths:
      - "tei/*.xml"

permissions:
  contents: read

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate TEI files
    steps:
      # We need to checkout with fetch-depth 0 or 2 for push events;
      # see https://github.com/tj-actions/changed-files?tab=readme-ov-file#usage-
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        if: github.event_name != 'push'

      - name: Get changed files
        id: changed-tei-files
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 #v47.0.1
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          files: |
            tei/*.xml

      - name: Get changed files
        id: all-tei-files
        if: github.event_name == 'workflow_dispatch'
        run: echo 'files=tei/*.xml' >> $GITHUB_OUTPUT

      - name: Validate against TEI-All schema
        uses: dracor-org/dracor-validate-action@5430d01df4e6dd52bb99d0bf9d94f09ad5a05ed1 # v2.1.0
        with:
          files: |
            ${{ steps.changed-tei-files.outputs.all_changed_files }}
            ${{ steps.all-tei-files.outputs.files }}

      - name: Validate against DraCor schema
        uses: dracor-org/dracor-validate-action@5430d01df4e6dd52bb99d0bf9d94f09ad5a05ed1 # v2.1.0
        with:
          files: |
            ${{ steps.changed-tei-files.outputs.all_changed_files }}
            ${{ steps.all-tei-files.outputs.files }}
          schema: dracor
          warn-only: yes
